### ISSUE TITLE
Problem - device connection

### ISSUE THREAD

**Issue by Tansey-ii** [UniBonn-GompelLab/FlyBehaviour#1]
Hi！ We plan to use the JAI-SP5000-USB camera with Matlab, but Matlab cannot recognize the camera. Could you tell us how you did it?

**Comment by S-Ceolin** [comment]
Hi Tansey, thanks for your interest! Unfortunately, this code was developed by a former member of the lab and it is not actively maintained, we can therefore provide very limited support. 

This Matlab program is used to control the acquisition of a camera supporting the GigE standard, these are cameras connected through an ethernet connection. Since you want to use a USB camera, I suppose you will have to change the adapter used by the videoinput object.

**Comment by UniBonn-GompelLab** [comment]
Hi Tansey, thanks for your interest! Unfortunately, this code was developed by a former member of the lab and it is not actively maintained, we can therefore provide very limited support.

This Matlab program is used to control the acquisition of a camera supporting the GigE standard, these are cameras connected through an ethernet connection. Since you want to use a USB camera, I suppose you will have to change the adapter used by the videoinput object.

**Comment by Tansey-ii** [comment]
Thanks for your reply!  I have successfully connected my camera to Matlab. Have you ever tried connecting two cameras at the same time with Matlab?

**Comment by UniBonn-GompelLab** [comment]
Hi Tansey, we have never tried to use multiple cameras. If you want to use them at the same time you will probably have to edit the code extensively. 
Best
